### ISSUE TITLE
Attempted install on cluster

### ISSUE THREAD

**Issue by cuperusj** [LaoZZZZZ/bartender-1.1#62]
Our IT has had issues installing:
" consistently get the same error despite using various combinations of OS, gcc and boost versions to compile this software:
bartender_single: src/bartender_single.cpp:174: int main(int, char**): Assertion `argc >= 3' failed."

**Comment by LaoZZZZZ** [comment]
Could you share more information how you get this error? It seems to me that bartender was already installed. And this error was triggered when running the program.

**Comment by cuperusj** [comment]
Let me see if I can connect my IT guys, I have been running it locally, but is maxing out my local machine, if you have recommendations to speed things up I am all ears.

This is 50 nucleotide random sequence library, 2 million or more uniques expected, 180 million single end reads.

bartender_single_com -f Lib2_input.csv -o input_Lb2 -t 4 -d 8 -z -1 -c 1

**Comment by LaoZZZZZ** [comment]
Hi Cuperusj,

Based on your command options, there are three options you can tune for higher speed.
One is thread number option -t. Theoretically you can use 2 * (# of cores) as the thread numbers. 
Another one is -s, which control the number of non-overlapping positions between two adjacent seeds. See README for more detail.  But this option also might affect accuracy.
The third one is seed length. The default value is 5. As the barcode length is 50, you can try something between 6, 7 or 8 for higher speed.

**Comment by LaoZZZZZ** [comment]
Close this issue. As it is more like a problem about how to use Bartender than an installation problem.

My guess is that the bartender_single(the c++ binary) was run directly but bartender_single_com (the python script) should be used instead.
