### ISSUE TITLE
Can you extract the sequencing depth at each time point from bartender?

### ISSUE THREAD

**Issue by loukesio** [LaoZZZZZ/bartender-1.1#74]
Dear Lao, 

Thank you for your package. Can someone extract the sequencing depth over time through bartender?
Looking forward to your answer

with best wishes,

**Comment by LaoZZZZZ** [comment]
Unfortunately Bartender does not provide estimation of sequencing depth or coverage. It's purely barcode counting tool. There are many parameters (i.e genome size and complexity)  that affect the sequence depth and none of them are processed by Bartender.
