### ISSUE TITLE
regex_error

### ISSUE THREAD

**Issue by jweile** [LaoZZZZZ/bartender-1.1#75]
Hi, I just tried to install and run bartender, but following the example provided in the README file, i ran into a "regex_error" in the extraction step: 

```
$ bartender_extractor_com -f 2M_test.fq -o 2M_extracted -q ? -p TACC[4-7]AA[4-7]AA[4-7]TT[4-7]ATAA -m 2
Running bartender extractor
bartender_extractor 2M_test.fq 2M_extracted 63 "(TAC.|TA.C|T.CC|.ACC)([ATCGN]{4,7})(AA)([ATCGN]{4,7})(AA)([ATCGN]{4,7})(TT)([ATCGN]{4,7})(ATA.|AT.A|A.AA|.TAA)" TACC ATAA 9 1  
terminate called after throwing an instance of 'std::regex_error'
  what():  regex_error
```

OS version is CentOS 7 (Core), kernel 3.10.0-1062.9.1.el7.x86_64

GCC version is 4.8.5 20150623 (Red Hat 4.8.5-39)

Thanks for your help!

**Comment by LaoZZZZZ** [comment]
Unfortunately bartender does not work well with CentOS, which has quite old GCC (https://distrowatch.com/table.php?distribution=centos). Please try other linux systems that have up-to-date GCC compilers
