### ISSUE TITLE
Unable to build bartender_single on Ubuntu 21.10

### ISSUE THREAD

**Issue by pol-delta** [LaoZZZZZ/bartender-1.1#76]
Extractor and Combiner both build correctly, but `make bartender_single` fails on Ubuntu 21.10. `make bartender_single` gives the following error that I've attached as an image:

![bartender-error](https://user-images.githubusercontent.com/87668279/147603435-bbbd572d-7069-48e9-ac30-3f56f5d0e31f.png)

Adding `#include <cstdint>` to mixturebptester.cpp and mixturebptester.h gets rid of that part of the error, but the other errors like size_t being undeclared, etc. are still there.

**Comment by ttyskg** [comment]
Hi @pol-delta, I also had the same issue, and I made pull request #77.

That modification worked in my environment (Debian 10). I hope it will also work in your environment.

**Comment by s-christel** [comment]
@ttyskg you are a life saver! worked for me on a Ubuntu22.04 under windows

**Comment by LaoZZZZZ** [comment]
It has been fixed by https://github.com/LaoZZZZZ/bartender-1.1/pull/77.
