### ISSUE TITLE
Regex Error

### ISSUE THREAD

**Issue by munmunbhasin** [LaoZZZZZ/bartender-1.1#78]
Hi, I just tried to install and run bartender, but following the example provided in the README file, I ran into a "regex_error" in the extraction step:

$ bartender_extractor_com -f 2M_test.fq -o 2M_extracted -q ? -p TACC[4-7]AA[4-7]AA[4-7]TT[4-7]ATAA -m 2
Running bartender extractor
bartender_extractor 2M_test.fq 2M_extracted 63 "(TAC.|TA.C|T.CC|.ACC)([ATCGN]{4,7})(AA)([ATCGN]{4,7})(AA)([ATCGN]{4,7})(TT)([ATCGN]{4,7})(ATA.|AT.A|A.AA|.TAA)" TACC ATAA 9 1  
terminate called after throwing an instance of 'std::regex_error'
  what():  regex_error

OS version is CentOS 7 (Core)
gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-44)

Please help me resolve this problem. Thanks for your help!

**Comment by LaoZZZZZ** [comment]
CentOS has pretty old GCC compiler, that does not support std::regex well. Please try other linux system that has up-to-date GCC compilers.
