### ISSUE TITLE
"problem with python"

### ISSUE THREAD

**Issue by ss-91** [LaoZZZZZ/bartender-1.1#79]
Hi,

When I try to run bartender_extractor_com I get the following error:
"-bash: bartender-1.1-master/bartender_extractor_com: /usr/bin/python: bad interpreter: No such file or directory"

I checked my python installation and deactivated the conda environment.
I have "/usr/bin/python3" directory, but not "/usr/bin/python."

I also tried to alias python with python3 and the problem still persists.

Here is my system information:
macOS Monterey 12.5

Apple clang version 13.0.0 (clang-1300.0.29.30)
Target: x86_64-apple-darwin21.6.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin

Python 3.10.7

I would be glad if you could help me with this issue. Thank you.

**Comment by LaoZZZZZ** [comment]
Hi there,

I think the most straightforward approach is to edit the local copy of bartender_extractor_com to point to /usr/bin/python3. 

Please update the issue once you tried it.

Thanks
Lu

**Comment by LaoZZZZZ** [comment]
The problem has been fixed.

**Comment by ss-91** [comment]
Hi,
 I am actually running into the same problem and editing the local copy of bartender_extractor_com to point to /usr/bin/python3 does not really help. Any further suggestions? 
 best,
Serkan

**Comment by LaoZZZZZ** [comment]
Did you try /usr/bin/env python  when editing bartender_extractor_com script?
